name: ci

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validation:
    name: centralized validation
    uses: qtrpartners/jarvis-automation/.github/workflows/jarvis-ci.yml@b60d42913edbd65c1c2b2f231c24540d4684216e
    permissions:
      contents: read
